import React, { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import {
  Bot,
  Wand2,
  Loader2,
  Sparkles,
  X,
  CheckCircle2,
  FileCode2,
  Code2,
  Database,
  Globe,
} from "lucide-react";

interface AutoArchitectModalProps {
  onClose: () => void;
  onComplete: (prompt: string, generatedFiles: any[]) => void;
}

export function AutoArchitectModal({
  onClose,
  onComplete,
}: AutoArchitectModalProps) {
  const [mode, setMode] = useState<"create" | "edit">("create");
  const [prompt, setPrompt] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [step, setStep] = useState(-1);
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [config, setConfig] = useState({
    architecture: "monolith",
    database: "atos_native",
    includeAuth: true,
    targetSystem: "a-townchain",
    customSystemName: "",
    designStyle: "tech",
    primaryColor: "#06b6d4",
    features: {
      pwa: false,
      websockets: false,
      graphql: false,
      payment: false,
      analytics: false,
      audio: false,
    },
  });

  const STEPS = [
    {
      label: "Analyse der Anforderungen...",
      icon: Bot,
      color: "text-purple-400",
    },
    {
      label: "Auswertung der Architektur-Spezifikationen...",
      icon: Globe,
      color: "text-blue-400",
    },
    {
      label: "Generierung der Datenbankschemata...",
      icon: Database,
      color: "text-orange-400",
    },
    {
      label: "Aufbau der Backend-Infrastruktur...",
      icon: FileCode2,
      color: "text-emerald-400",
    },
    {
      label: "Erstellung der Frontend-Komponenten...",
      icon: Code2,
      color: "text-cyan-400",
    },
    {
      label: "Verknüpfung und ATC-Kompilierung...",
      icon: Wand2,
      color: "text-amber-400",
    },
  ];

  const handleGenerate = () => {
    if (!prompt.trim()) return;
    setIsGenerating(true);
    setStep(0);

    let currentStep = 0;
    const interval = setInterval(() => {
      currentStep++;
      setStep(currentStep);

      if (currentStep >= STEPS.length) {
        clearInterval(interval);
        setTimeout(() => {
          // Generate dummy files based on prompt and config
          const sanitizedTitle =
            prompt
              .split(" ")[0]
              .toLowerCase()
              .replace(/[^a-z0-9]/g, "") || "app";
          const dbExt =
            config.database === "sql"
              ? "sql"
              : config.database === "nosql"
                ? "json"
                : "atc";
          const targetOS =
            config.targetSystem === "custom"
              ? config.customSystemName || "Eigene System"
              : config.targetSystem;

          const generatedFiles = [
            {
              name: `src/backend/${sanitizedTitle}_api.ts`,
              content: `// AUTOGENERATED API\n// Target System: ${targetOS}\n// Arch: ${config.architecture}\nimport express from 'express';\n\nconst router = express.Router();\n\nrouter.get('/', (req, res) => {\n  res.json({ status: 'active', module: '${sanitizedTitle}' });\n});\n\nexport default router;`,
              iconColor: "text-emerald-400",
              iconShape: "⚡",
            },
            {
              name: `src/frontend/${sanitizedTitle}_view.tsx`,
              content: `// AUTOGENERATED VIEW\nimport React from 'react';\n\nexport function ${sanitizedTitle.charAt(0).toUpperCase() + sanitizedTitle.slice(1)}View() {\n  return (\n    <div className="p-4 rounded-xl" style={{ backgroundColor: '${config.designStyle === "dark" || config.designStyle === "tech" ? "#0f172a" : "#f8fafc"}', borderColor: '${config.primaryColor}', borderWidth: '2px' }}>\n      <h2 className="text-xl font-bold" style={{ color: '${config.primaryColor}' }}>Autogenerated Module: ${sanitizedTitle}</h2>\n      <p className="text-slate-400 mt-2">Architecture: ${config.architecture}</p>\n      <p className="text-slate-400 mt-1">Target OS: ${targetOS}</p>\n      <p className="text-slate-400 mt-1">Design Style: ${config.designStyle}</p>\n    </div>\n  );\n}`,
              iconColor: "text-cyan-400",
              iconShape: "⚛",
            },
            {
              name: `config/${sanitizedTitle}_schema.${dbExt}`,
              content: `@Entity ${sanitizedTitle} {\n  id: UUID;\n  createdAt: Timestamp;\n  status: String;\n}\n`,
              iconColor: "text-orange-400",
              iconShape: "📜",
            },
          ];

          if (config.includeAuth) {
            generatedFiles.push({
              name: `src/backend/auth_service.ts`,
              content: `// AUTOGENERATED AUTHENTICATION LAYER\nexport function verifyToken(token: string) {\n  return true;\n}\n`,
              iconColor: "text-purple-400",
              iconShape: "🔒",
            });
          }

          if (config.features.pwa) {
            generatedFiles.push({
              name: `public/service-worker.js`,
              content: `// AUTOGENERATED PWA SERVICE WORKER\nself.addEventListener('install', (e) => {\n  console.log('[PWA] Installed');\n});\n`,
              iconColor: "text-blue-400",
              iconShape: "📱",
            });
          }
          if (config.features.websockets) {
            generatedFiles.push({
              name: `src/backend/websocket.ts`,
              content: `// AUTOGENERATED WEBSOCKET SERVER\nexport function initWebSockets(server: any) {\n  console.log('[WS] Initialized');\n}\n`,
              iconColor: "text-cyan-400",
              iconShape: "🔌",
            });
          }
          if (config.features.graphql) {
            generatedFiles.push({
              name: `src/backend/schema.graphql`,
              content: `type Query {\n  hello: String\n}\n\ntype Mutation {\n  create(input: String): String\n}\n`,
              iconColor: "text-pink-400",
              iconShape: "🧬",
            });
          }
          if (config.features.payment) {
            generatedFiles.push({
              name: `src/backend/payment.ts`,
              content: `// AUTOGENERATED STRIPE PAYMENT ROUTE\nexport async function processPayment(amount: number) {\n  return { success: true, transactionId: 'txn_' + Date.now() };\n}\n`,
              iconColor: "text-emerald-400",
              iconShape: "💳",
            });
          }
          if (config.features.audio) {
            generatedFiles.push({
              name: `src/utils/audio_engine.ts`,
              content: `// AUTOGENERATED AUDIO ENGINE\nexport class AudioEngine {\n  play(trackId: string) { console.log('Playing', trackId); }\n  stop() { console.log('Stopped'); }\n}\n`,
              iconColor: "text-violet-400",
              iconShape: "🔈",
            });
          }

          if (mode === "edit") {
            generatedFiles.push({
              name: `src/utils/patch-log.txt`,
              content: `// AUTOGENERATED PATCH LOG\nDate: ${new Date().toISOString()}\nChanges applied: \n- ${prompt}\n`,
              iconColor: "text-amber-400",
              iconShape: "📝",
            });
          }

          onComplete(prompt, generatedFiles);
        }, 800);
      }
    }, 1200);
  };

  return (
    <div className="fixed inset-0 z-[200] flex items-center justify-center bg-black/80 backdrop-blur-md font-sans">
      <motion.div
        initial={{ scale: 0.9, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        exit={{ scale: 0.9, opacity: 0 }}
        className="bg-[#0c0c0e] border border-white/10 rounded-xl shadow-2xl overflow-hidden max-w-lg w-full mx-4 flex flex-col"
      >
        {/* Header */}
        <div className="px-6 py-4 border-b border-white/10 flex items-center justify-between bg-white/[0.02]">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-purple-500/10 rounded-lg">
              <Sparkles className="w-5 h-5 text-purple-400" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-slate-200">
                Automatische Softwareschmiede
              </h2>
              <p className="text-[11px] uppercase tracking-wider text-slate-500">
                ATC-FSS Auto-Architect
              </p>
            </div>
          </div>
          {!isGenerating && (
            <div className="flex bg-black/50 p-1 rounded-lg border border-white/10">
              <button
                onClick={() => setMode("create")}
                className={`px-3 py-1 rounded text-xs font-bold transition-all ${
                  mode === "create"
                    ? "bg-purple-500/20 text-purple-400"
                    : "text-slate-500 hover:text-slate-300"
                }`}
              >
                Erstellen
              </button>
              <button
                onClick={() => setMode("edit")}
                className={`px-3 py-1 rounded text-xs font-bold transition-all ${
                  mode === "edit"
                    ? "bg-purple-500/20 text-purple-400"
                    : "text-slate-500 hover:text-slate-300"
                }`}
              >
                Bearbeiten
              </button>
            </div>
          )}
          {!isGenerating && (
            <button
              onClick={onClose}
              className="p-2 text-slate-500 hover:text-red-400 hover:bg-white/5 rounded-lg transition-colors ml-4"
            >
              <X className="w-5 h-5" />
            </button>
          )}
        </div>

        {/* Content */}
        <div className="p-6">
          {!isGenerating ? (
            <div className="space-y-4">
              <p className="text-sm text-slate-300">
                {mode === "create"
                  ? "Beschreibe dein Software-Projekt. Der ATOS AI-Agent wird automatisch die Architektur entwerfen, das Backend programmieren, das Frontend generieren und alle Module verknüpfen."
                  : "Beschreibe, welche Änderungen oder neuen Features zur bestehenden Software hinzugefügt werden sollen."}
              </p>
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder={
                  mode === "create"
                    ? "z.B. Ein dezentrales Chat-System mit Verschlüsselung und Datei-Transfer..."
                    : "z.B. Füge ein neues Admin-Dashboard hinzu und ändere die Farben..."
                }
                className="w-full h-32 bg-black/50 border border-white/10 rounded-lg p-3 text-sm text-slate-200 placeholder-slate-600 focus:outline-none focus:border-purple-500/50 resize-none"
              />

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="text-xs text-slate-400 font-bold uppercase tracking-wider">
                    Zielsystem
                  </label>
                  <select
                    value={config.targetSystem}
                    onChange={(e) =>
                      setConfig({ ...config, targetSystem: e.target.value })
                    }
                    className="w-full bg-black/50 border border-white/10 rounded-lg px-3 py-2 text-sm text-slate-200 focus:outline-none focus:border-purple-500/50"
                  >
                    <option value="windows">Windows</option>
                    <option value="macos">macOS</option>
                    <option value="linux">Linux</option>
                    <option value="android">Android</option>
                    <option value="a-townchain">A-TownChain (KAI-OS)</option>
                    <option value="custom">Eigene Betriebssystem</option>
                  </select>
                </div>

                <div className="space-y-2">
                  <label className="text-xs text-slate-400 font-bold uppercase tracking-wider">
                    Design Style
                  </label>
                  <select
                    value={config.designStyle}
                    onChange={(e) =>
                      setConfig({ ...config, designStyle: e.target.value })
                    }
                    className="w-full bg-black/50 border border-white/10 rounded-lg px-3 py-2 text-sm text-slate-200 focus:outline-none focus:border-purple-500/50"
                  >
                    <option value="minimal">Minimalist</option>
                    <option value="dark">Dark Mode</option>
                    <option value="tech">High-Tech / Cyber</option>
                    <option value="corporate">Corporate</option>
                  </select>
                </div>
              </div>

              <div className="flex gap-4">
                {config.targetSystem === "custom" && (
                  <div className="flex-1 space-y-2">
                    <label className="text-xs text-slate-400 font-bold uppercase tracking-wider">
                      Systemname
                    </label>
                    <input
                      type="text"
                      value={config.customSystemName}
                      onChange={(e) =>
                        setConfig({
                          ...config,
                          customSystemName: e.target.value,
                        })
                      }
                      placeholder="Name des Betriebssystems..."
                      className="w-full bg-black/50 border border-white/10 rounded-lg px-3 py-2 text-sm text-slate-200 focus:outline-none focus:border-purple-500/50"
                    />
                  </div>
                )}
                <div
                  className={`${config.targetSystem === "custom" ? "w-32" : "w-full"} space-y-2`}
                >
                  <label className="text-xs text-slate-400 font-bold uppercase tracking-wider">
                    Hauptfarbe
                  </label>
                  <div className="flex items-center gap-2">
                    <input
                      type="color"
                      value={config.primaryColor}
                      onChange={(e) =>
                        setConfig({ ...config, primaryColor: e.target.value })
                      }
                      className="w-8 h-8 rounded border border-white/10 bg-transparent cursor-pointer"
                    />
                    <span className="text-sm font-mono text-slate-400">
                      {config.primaryColor}
                    </span>
                  </div>
                </div>
              </div>

              <div className="border border-white/10 rounded-lg overflow-hidden">
                <button
                  onClick={() => setShowAdvanced(!showAdvanced)}
                  className="w-full flex items-center justify-between p-3 bg-white/5 hover:bg-white/10 transition-colors text-sm font-medium text-slate-300"
                >
                  <span>Erweiterte Architektur-Einstellungen</span>
                  <span className="text-xs text-slate-500">
                    {showAdvanced ? "Verbergen" : "Anzeigen"}
                  </span>
                </button>
                <AnimatePresence>
                  {showAdvanced && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      className="p-4 bg-black/30 border-t border-white/10 space-y-4"
                    >
                      <div className="space-y-2">
                        <label className="text-xs text-slate-400 font-bold uppercase tracking-wider">
                          Architektur-Muster
                        </label>
                        <select
                          value={config.architecture}
                          onChange={(e) =>
                            setConfig({
                              ...config,
                              architecture: e.target.value,
                            })
                          }
                          className="w-full bg-white/5 border border-white/10 rounded px-3 py-2 text-sm text-slate-300 focus:outline-none focus:border-cyan-500"
                        >
                          <option value="monolith">
                            Standard-Monolith (Express/React)
                          </option>
                          <option value="microservices">
                            Microservices (Dockerized)
                          </option>
                          <option value="serverless">
                            Serverless Functions
                          </option>
                        </select>
                      </div>

                      <div className="space-y-2">
                        <label className="text-xs text-slate-400 font-bold uppercase tracking-wider">
                          Storage-Layer
                        </label>
                        <select
                          value={config.database}
                          onChange={(e) =>
                            setConfig({ ...config, database: e.target.value })
                          }
                          className="w-full bg-white/5 border border-white/10 rounded px-3 py-2 text-sm text-slate-300 focus:outline-none focus:border-cyan-500"
                        >
                          <option value="atos_native">
                            ATC-FSS Native (.atc)
                          </option>
                          <option value="sql">
                            Relational (PostgreSQL/MySQL)
                          </option>
                          <option value="nosql">
                            Dokumenten-Store (MongoDB)
                          </option>
                        </select>
                      </div>

                      <div className="flex items-center gap-2 pt-2">
                        <input
                          type="checkbox"
                          id="auth_toggle"
                          checked={config.includeAuth}
                          onChange={(e) =>
                            setConfig({
                              ...config,
                              includeAuth: e.target.checked,
                            })
                          }
                          className="w-4 h-4 rounded border-white/10 bg-black/50 accent-cyan-500"
                        />
                        <label
                          htmlFor="auth_toggle"
                          className="text-sm text-slate-300 cursor-pointer"
                        >
                          Integrierte Authentifizierung (JWT) hinzufügen
                        </label>
                      </div>

                      <div className="space-y-2 pt-4 border-t border-white/10">
                        <label className="text-xs text-slate-400 font-bold uppercase tracking-wider">
                          Weitere Features (Optional)
                        </label>
                        <div className="grid grid-cols-2 gap-3 mt-2">
                          <label className="flex items-center gap-2 cursor-pointer">
                            <input
                              type="checkbox"
                              checked={config.features.pwa}
                              onChange={(e) =>
                                setConfig({
                                  ...config,
                                  features: {
                                    ...config.features,
                                    pwa: e.target.checked,
                                  },
                                })
                              }
                              className="w-4 h-4 rounded border-white/10 bg-black/50 accent-cyan-500"
                            />
                            <span className="text-sm text-slate-300">
                              PWA (Offline)
                            </span>
                          </label>
                          <label className="flex items-center gap-2 cursor-pointer">
                            <input
                              type="checkbox"
                              checked={config.features.websockets}
                              onChange={(e) =>
                                setConfig({
                                  ...config,
                                  features: {
                                    ...config.features,
                                    websockets: e.target.checked,
                                  },
                                })
                              }
                              className="w-4 h-4 rounded border-white/10 bg-black/50 accent-cyan-500"
                            />
                            <span className="text-sm text-slate-300">
                              WebSockets
                            </span>
                          </label>
                          <label className="flex items-center gap-2 cursor-pointer">
                            <input
                              type="checkbox"
                              checked={config.features.graphql}
                              onChange={(e) =>
                                setConfig({
                                  ...config,
                                  features: {
                                    ...config.features,
                                    graphql: e.target.checked,
                                  },
                                })
                              }
                              className="w-4 h-4 rounded border-white/10 bg-black/50 accent-cyan-500"
                            />
                            <span className="text-sm text-slate-300">
                              GraphQL API
                            </span>
                          </label>
                          <label className="flex items-center gap-2 cursor-pointer">
                            <input
                              type="checkbox"
                              checked={config.features.payment}
                              onChange={(e) =>
                                setConfig({
                                  ...config,
                                  features: {
                                    ...config.features,
                                    payment: e.target.checked,
                                  },
                                })
                              }
                              className="w-4 h-4 rounded border-white/10 bg-black/50 accent-cyan-500"
                            />
                            <span className="text-sm text-slate-300">
                              Stripe Payment
                            </span>
                          </label>
                          <label className="flex items-center gap-2 cursor-pointer">
                            <input
                              type="checkbox"
                              checked={config.features.analytics}
                              onChange={(e) =>
                                setConfig({
                                  ...config,
                                  features: {
                                    ...config.features,
                                    analytics: e.target.checked,
                                  },
                                })
                              }
                              className="w-4 h-4 rounded border-white/10 bg-black/50 accent-cyan-500"
                            />
                            <span className="text-sm text-slate-300">
                              Analytics
                            </span>
                          </label>
                          <label className="flex items-center gap-2 cursor-pointer">
                            <input
                              type="checkbox"
                              checked={config.features.audio}
                              onChange={(e) =>
                                setConfig({
                                  ...config,
                                  features: {
                                    ...config.features,
                                    audio: e.target.checked,
                                  },
                                })
                              }
                              className="w-4 h-4 rounded border-white/10 bg-black/50 accent-cyan-500"
                            />
                            <span className="text-sm text-slate-300">
                              Audio / Sound Engine
                            </span>
                          </label>
                        </div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>

              <button
                onClick={handleGenerate}
                disabled={!prompt.trim()}
                className="w-full py-3 bg-gradient-to-r from-purple-600 to-cyan-600 hover:from-purple-500 hover:to-cyan-500 text-white rounded-lg font-bold shadow-lg shadow-purple-500/20 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                <Wand2 className="w-4 h-4" />
                {mode === "create"
                  ? "Software automatisch erstellen"
                  : "Software aktualisieren & anwenden"}
              </button>
            </div>
          ) : (
            <div className="py-4 flex flex-col items-center">
              <div className="w-16 h-16 relative mb-8">
                <div className="absolute inset-0 rounded-full border-4 border-white/5"></div>
                <div className="absolute inset-0 rounded-full border-4 border-purple-500 border-t-transparent animate-spin"></div>
                <div className="absolute inset-0 flex items-center justify-center">
                  <Bot className="w-6 h-6 text-cyan-400 animate-pulse" />
                </div>
              </div>

              <div className="w-full space-y-3">
                {STEPS.map((s, idx) => {
                  const isActive = idx === step;
                  const isDone = idx < step;
                  const isPending = idx > step;

                  return (
                    <div
                      key={idx}
                      className={`flex items-center gap-3 p-3 rounded-lg border ${isActive ? "bg-white/10 border-white/20" : isDone ? "bg-white/5 border-white/5" : "border-transparent opacity-40"}`}
                    >
                      {isDone ? (
                        <CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0" />
                      ) : isActive ? (
                        <Loader2
                          className={`w-5 h-5 ${s.color} animate-spin shrink-0`}
                        />
                      ) : (
                        <s.icon className="w-5 h-5 text-slate-600 shrink-0" />
                      )}
                      <span
                        className={`text-sm font-medium ${isActive ? "text-slate-200" : isDone ? "text-slate-400" : "text-slate-600"}`}
                      >
                        {s.label}
                      </span>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>
      </motion.div>
    </div>
  );
}
