import React, { useState } from 'react';
import { motion } from 'motion/react';
import { Gamepad2, X, Play, Settings2, Code2, Loader2, CheckCircle2 } from 'lucide-react';

interface GameScaffoldModalProps {
  onClose: () => void;
  onComplete: (genre: string, generatedFiles: any[]) => void;
}

export function GameScaffoldModal({ onClose, onComplete }: GameScaffoldModalProps) {
  const [selectedGenre, setSelectedGenre] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [step, setStep] = useState(-1);

  const GENRES = [
    { id: "arcade", label: "Classic Arcade (Snake, Pong)", desc: "Einfache 2D-Mechanik, Game-Loop, Kollisionsabfrage", icon: "🕹️" },
    { id: "platformer", label: "2D Platformer", desc: "Physik-Engine, Gravitation, Level-Tiles", icon: "🏃" },
    { id: "rpg", label: "Top-Down RPG", desc: "Grid-Movement, Inventar-System, NPC-Dialoge", icon: "⚔️" },
    { id: "puzzle", label: "Puzzle & Logic", desc: "State-Management, Grid-Logik, Score-System", icon: "🧩" },
    { id: "fps", label: "FPS Shooter", desc: "First-Person Kamera, Raycasting, Waffen-Logik", icon: "🔫" },
    { id: "racing", label: "Rennspiel", desc: "Fahrzeugphysik, Strecken-Logik, Checkpoints", icon: "🏎️" },
    { id: "action", label: "Action-Adventure", desc: "Kombat-System, Ausrüstung, Level-Phasen", icon: "💥" },
    { id: "horror", label: "Horror Game", desc: "Sichtfeld-Einschränkung, Inventar, Schreck-Logik", icon: "👻" },
    { id: "openworld", label: "Open World", desc: "Chunk-Loading, Quests, freies Bewegen", icon: "🌍" },
    { id: "3d", label: "General 3D", desc: "3D Rendering (Three.js/WebGL), Kamera, Modelle", icon: "🧊" }
  ];

  const STEPS = [
    { label: "Analysiere Genre-Anforderungen...", color: "text-purple-400" },
    { label: "Erstelle Game-Loop & Engine...", color: "text-blue-400" },
    { label: "Generiere Spiellogik & Physik...", color: "text-emerald-400" },
    { label: "Baue Frontend Rendering (React/Canvas)...", color: "text-cyan-400" },
    { label: "Verknüpfe Module...", color: "text-amber-400" }
  ];

  const handleGenerate = () => {
    if (!selectedGenre) return;
    setIsGenerating(true);
    setStep(0);

    let currentStep = 0;
    const interval = setInterval(() => {
      currentStep++;
      setStep(currentStep);

      if (currentStep >= STEPS.length) {
        clearInterval(interval);
        setTimeout(() => {
          const genreData = GENRES.find(g => g.id === selectedGenre);
          const generatedFiles = [
            { name: `src/game/engine.ts`, content: `// AUTOGENERATED GAME ENGINE\nexport class GameEngine {\n  private lastTime: number = 0;\n  private animationId: number = 0;\n  public onUpdate?: (deltaTime: number) => void;\n  \n  start() {\n    this.lastTime = performance.now();\n    this.loop(this.lastTime);\n  }\n\n  stop() {\n    cancelAnimationFrame(this.animationId);\n  }\n  \n  private loop = (time: number) => {\n    const delta = time - this.lastTime;\n    this.lastTime = time;\n    if (this.onUpdate) {\n      this.onUpdate(delta);\n    }\n    this.animationId = requestAnimationFrame(this.loop);\n  }\n}\n`, iconColor: 'text-emerald-400', iconShape: '⚙️' },
            { name: `src/game/${selectedGenre}_logic.ts`, content: `// AUTOGENERATED ${genreData?.label.toUpperCase()} LOGIC\nexport class GameLogic {\n  playerState: any = { x: 10, y: 10, speed: 5 };\n  \n  update(deltaTime: number) {\n    // Implement physics / logic for ${selectedGenre} here\n    // example: this.playerState.x += this.playerState.speed * (deltaTime/1000);\n  }\n}\n`, iconColor: 'text-orange-400', iconShape: '🧠' },
            { name: `src/frontend/GameView.tsx`, content: `// AUTOGENERATED GAME VIEW\nimport React, { useEffect, useRef, useState } from 'react';\nimport { GameEngine } from '../game/engine';\nimport { GameLogic } from '../game/${selectedGenre}_logic';\n\nexport function GameView() {\n  const engineRef = useRef<GameEngine | null>(null);\n  const logicRef = useRef<GameLogic | null>(null);\n  const [running, setRunning] = useState(false);\n  \n  useEffect(() => {\n    logicRef.current = new GameLogic();\n    engineRef.current = new GameEngine();\n    \n    engineRef.current.onUpdate = (dt) => {\n      logicRef.current?.update(dt);\n      // Update React state or draw to Canvas here\n    };\n    \n    return () => {\n      engineRef.current?.stop();\n    };\n  }, []);\n\n  const startGame = () => {\n    engineRef.current?.start();\n    setRunning(true);\n  };\n\n  return (\n    <div className="flex flex-col items-center justify-center h-full w-full bg-slate-900 border border-slate-700/50 rounded-xl">\n      <h2 className="text-xl font-bold text-cyan-400 mb-4">${genreData?.label} Engine</h2>\n      {!running ? (\n        <button onClick={startGame} className="px-4 py-2 bg-emerald-500/20 text-emerald-400 border border-emerald-500/50 hover:bg-emerald-500/30 font-bold rounded">\n          Spiel starten\n        </button>\n      ) : (\n        <div className="text-slate-400 text-sm">Spiel läuft im Hintergrund-Loop... (Bitte Rendering in Canvas / React einbauen)</div>\n      )}\n    </div>\n  );\n}`, iconColor: 'text-cyan-400', iconShape: '⚛' }
          ];
          
          onComplete(selectedGenre, generatedFiles);
        }, 800);
      }
    }, 800);
  };

  return (
    <div className="fixed inset-0 z-[200] flex items-center justify-center bg-black/80 backdrop-blur-md font-sans">
      <motion.div 
        initial={{ scale: 0.9, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        exit={{ scale: 0.9, opacity: 0 }}
        className="bg-[#0c0c0e] border border-white/10 rounded-xl shadow-2xl overflow-hidden max-w-4xl w-full mx-4 flex flex-col"
      >
        <div className="px-6 py-4 border-b border-white/10 flex items-center justify-between bg-white/[0.02]">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-emerald-500/10 rounded-lg">
              <Gamepad2 className="w-5 h-5 text-emerald-400" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-slate-200">Spiele-Gerüst Generator</h2>
              <p className="text-[11px] uppercase tracking-wider text-slate-500">ATC-Game-Architect</p>
            </div>
          </div>
          {!isGenerating && (
            <button onClick={onClose} className="p-2 text-slate-500 hover:text-red-400 hover:bg-white/5 rounded-lg transition-colors">
              <X className="w-5 h-5" />
            </button>
          )}
        </div>

        <div className="p-6">
          {!isGenerating ? (
            <div className="space-y-6">
              <p className="text-sm text-slate-300">
                Wähle ein Spiel-Genre. Der Agent wird automatisch die Grundfunktionen (Game-Loop, Rendering, Logik) erstellen, die du beliebig anpassen kannst.
              </p>

              <div className="grid grid-cols-2 lg:grid-cols-3 gap-4 max-h-[50vh] overflow-y-auto pr-2">
                {GENRES.map(genre => (
                  <div 
                    key={genre.id}
                    onClick={() => setSelectedGenre(genre.id)}
                    className={`cursor-pointer p-4 rounded-xl border transition-all ${selectedGenre === genre.id ? 'bg-emerald-500/10 border-emerald-500' : 'bg-white/5 border-white/10 hover:border-white/30'}`}
                  >
                    <div className="flex justify-between items-start mb-2">
                      <div className="text-2xl">{genre.icon}</div>
                      {selectedGenre === genre.id && <CheckCircle2 className="w-5 h-5 text-emerald-400" />}
                    </div>
                    <h3 className={`font-bold ${selectedGenre === genre.id ? 'text-emerald-400' : 'text-slate-200'}`}>{genre.label}</h3>
                    <p className="text-xs text-slate-500 mt-1">{genre.desc}</p>
                  </div>
                ))}
              </div>

              <button
                onClick={handleGenerate}
                disabled={!selectedGenre}
                className="w-full py-3 bg-gradient-to-r from-emerald-600 to-cyan-600 hover:from-emerald-500 hover:to-cyan-500 text-white rounded-lg font-bold shadow-lg shadow-emerald-500/20 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2 mt-4"
              >
                <Code2 className="w-4 h-4" />
                Grundfunktionen für Spiel erstellen
              </button>
            </div>
          ) : (
            <div className="py-8 flex flex-col items-center">
              <div className="w-16 h-16 relative mb-8">
                <div className="absolute inset-0 rounded-full border-4 border-white/5"></div>
                <div className="absolute inset-0 rounded-full border-4 border-emerald-500 border-t-transparent animate-spin"></div>
                <div className="absolute inset-0 flex items-center justify-center">
                  <Gamepad2 className="w-6 h-6 text-cyan-400 animate-pulse" />
                </div>
              </div>

              <div className="w-full space-y-3 max-w-md">
                {STEPS.map((s, idx) => {
                  const isActive = idx === step;
                  const isDone = idx < step;
                  
                  return (
                    <div key={idx} className={`flex items-center gap-3 p-3 rounded-lg border ${isActive ? 'bg-white/10 border-white/20' : isDone ? 'bg-white/5 border-white/5' : 'border-transparent opacity-40'}`}>
                      {isDone ? (
                        <CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0" />
                      ) : isActive ? (
                        <Loader2 className={`w-5 h-5 ${s.color} animate-spin shrink-0`} />
                      ) : (
                        <div className="w-5 h-5 rounded-full border-2 border-slate-600 shrink-0" />
                      )}
                      <span className={`text-sm font-medium ${isActive ? 'text-slate-200' : isDone ? 'text-slate-400' : 'text-slate-600'}`}>
                        {s.label}
                      </span>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>
      </motion.div>
    </div>
  );
}
